Document: multimarkdown
Title: Debian multimarkdown Manual
Author: <insert document author here>
Abstract: This manual describes what multimarkdown is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/multimarkdown/multimarkdown.sgml.gz

Format: postscript
Files: /usr/share/doc/multimarkdown/multimarkdown.ps.gz

Format: text
Files: /usr/share/doc/multimarkdown/multimarkdown.text.gz

Format: HTML
Index: /usr/share/doc/multimarkdown/html/index.html
Files: /usr/share/doc/multimarkdown/html/*.html
